        lw      0       1       var1    // Load var1 to reg1
        sw      0       1       var2    // Store reg1 to var2
        lw      0       2       var3    // Load var3 to reg2
        sw      0       2       var4    // Store reg2 to var4
        lw      0       3       var5    // Load var5 to reg3
        sw      0       3       var6    // Store reg3 to var6
        lw      0       4       var7    // Load var7 to reg4
        sw      0       4       var8    // Store reg4 to var8
        lw      0       5       var9    // Load var9 to reg5
        sw      0       5       var10   // Store reg5 to var10
        halt                           // Halt the program
var1    .fill   1             // Initialize var1 with value 1
var2    .fill   0             // Initialize var2 with value 0
var3    .fill   2             // Initialize var3 with value 2
var4    .fill   0             // Initialize var4 with value 0
var5    .fill   3             // Initialize var5 with value 3
var6    .fill   0             // Initialize var6 with value 0
var7    .fill   4             // Initialize var7 with value 4
var8    .fill   0             // Initialize var8 with value 0
var9    .fill   5             // Initialize var9 with value 5
var10   .fill   0             // Initialize var10 with value 0
